version: '3'

services:
  db:
    platform: linux/x86_64
    image: mysql:8.0.26
    environment:
      MYSQL_DATABASE: django_db
      MYSQL_PASSWORD: password
      MYSQL_ALLOW_EMPTY_PASSWORD: ‘yes’
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql

  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
    extra_hosts: # 追加
      - localhost:192.168.96.1   # 追加

volumes:
  data: